services:
  # ======================
  # FastAPI Backend (GPU)
  # ======================
  connector:
    build:
      context: ../FastApi
      dockerfile: ../docker/DockerFile.backend
    container_name: connector
    volumes:
      - ./models:/models
    restart: unless-stopped
    ports:
      - "8001:8000"
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
    depends_on:
      - redis
      - postgres
    networks:
      - bpai_shared_net
 
  # ======================
  # Celery Worker (CPU ONLY)
  # ======================
  celery-worker:
    build:
      context: ../FastApi
      dockerfile: ../docker/DockerFile.backend

    container_name: celery-worker
    restart: unless-stopped

    command: >
      celery -A app.celery worker
      --loglevel=info
      --concurrency=4
      --prefetch-multiplier=1
      --max-tasks-per-child=50

    env_file:
      - ./.env

    depends_on:
      - redis
      - postgres

    networks:
      - bpai_shared_net

  # ======================
  # Celery Beat (CPU ONLY)
  # ======================
  celery-beat:
    build:
      context: ../FastApi
      dockerfile: ../docker/DockerFile.backend

    container_name: celery-beat
    restart: unless-stopped

    command: >
      celery -A app.celery beat
      --loglevel=info
      --schedule=/tmp/celerybeat-schedule

    env_file:
      - ./.env

    depends_on:
      - redis
      - postgres

    networks:
      - bpai_shared_net


  # ======================
  # PostgreSQL
  # ======================
  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    container_name: postgres-local
    restart: unless-stopped
    environment:
      POSTGRES_USER: bpai
      POSTGRES_PASSWORD: bpai
      POSTGRES_DB: bpai
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bpai_shared_net

  # ======================
  # Redis
  # ======================
  redis:
    image: redis:7
    container_name: redis-server
    restart: unless-stopped

    ports:
      - "6379:6379"

    command: >
      redis-server
      --appendonly yes
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru

    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - bpai_shared_net


  # ======================
  # Frontend
  # ======================
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/DockerFile.frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - bpai_shared_net


  # ======================
  # Ollama (GPU)
  # ======================
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-gpu
    restart: unless-stopped
    ports:
      - "11434:11434"

    environment:
      OLLAMA_HOST: "0.0.0.0"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility

    gpus: all

    volumes:
      - ollama-data:/root/.ollama

    networks:
      - bpai_shared_net


  # ======================
  # OpenWebUI
  # ======================
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    ports:
      - "3002:8080"
    networks:
      - bpai_shared_net

  # ======================
  # clickhouse
  # ======================
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    environment:
      CLICKHOUSE_DB: connector
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
      CLICKHOUSE_USER: bpai
      CLICKHOUSE_PASSWORD: bpai
    networks:
      - bpai_shared_net
  
  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    restart: unless-stopped
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
    ports:
      - "6433:6432"
    depends_on:
      - postgres
    networks:
      - bpai_shared_net
# ======================
# Volumes
# ======================
volumes:
  pgdata:
  ollama-data:
  clickhouse_data:
  clickhouse_logs:
  redis_data:
# ======================
# Network
# ======================
networks:
  bpai_shared_net:
    # external: true
 
