# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import activity_pb2 as activity__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in activity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ActivityServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetConversation = channel.unary_unary(
                '/activity.ActivityService/GetConversation',
                request_serializer=activity__pb2.ConversationRequest.SerializeToString,
                response_deserializer=activity__pb2.ConversationResponse.FromString,
                _registered_method=True)
        self.StreamConversation = channel.unary_stream(
                '/activity.ActivityService/StreamConversation',
                request_serializer=activity__pb2.ConversationRequest.SerializeToString,
                response_deserializer=activity__pb2.Activity.FromString,
                _registered_method=True)


class ActivityServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetConversation(self, request, context):
        """Existing unary RPC (keep for backward compatibility)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamConversation(self, request, context):
        """NEW: Server-side streaming RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActivityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConversation,
                    request_deserializer=activity__pb2.ConversationRequest.FromString,
                    response_serializer=activity__pb2.ConversationResponse.SerializeToString,
            ),
            'StreamConversation': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamConversation,
                    request_deserializer=activity__pb2.ConversationRequest.FromString,
                    response_serializer=activity__pb2.Activity.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'activity.ActivityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('activity.ActivityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ActivityService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/activity.ActivityService/GetConversation',
            activity__pb2.ConversationRequest.SerializeToString,
            activity__pb2.ConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/activity.ActivityService/StreamConversation',
            activity__pb2.ConversationRequest.SerializeToString,
            activity__pb2.Activity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
