# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: activity.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'activity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61\x63tivity.proto\x12\x08\x61\x63tivity\"\x9d\x01\n\x13\x43onversationRequest\x12\x0c\n\x04id_1\x18\x01 \x01(\t\x12\x0c\n\x04id_2\x18\x02 \x01(\t\x12#\n\x08\x63hannels\x18\x03 \x03(\x0e\x32\x11.activity.Channel\x12&\n\tdirection\x18\x04 \x01(\x0e\x32\x13.activity.Direction\x12\r\n\x05limit\x18\x05 \x01(\x05\x12\x0e\n\x06offset\x18\x06 \x01(\x05\"\x89\x01\n\x08\x41\x63tivity\x12\x13\n\x0b\x61\x63tivity_id\x18\x01 \x01(\t\x12\"\n\x07\x63hannel\x18\x02 \x01(\x0e\x32\x11.activity.Channel\x12\x0e\n\x06sender\x18\x03 \x01(\t\x12\x10\n\x08receiver\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\"M\n\x14\x43onversationResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12&\n\nactivities\x18\x02 \x03(\x0b\x32\x12.activity.Activity*E\n\x07\x43hannel\x12\x17\n\x13\x43HANNEL_UNSPECIFIED\x10\x00\x12\t\n\x05\x45MAIL\x10\x01\x12\x0c\n\x08WHATSAPP\x10\x02\x12\x08\n\x04\x43\x41LL\x10\x03*6\n\tDirection\x12\x11\n\rDIRECTION_ANY\x10\x00\x12\x08\n\x04SENT\x10\x01\x12\x0c\n\x08RECEIVED\x10\x02\x32\xae\x01\n\x0f\x41\x63tivityService\x12P\n\x0fGetConversation\x12\x1d.activity.ConversationRequest\x1a\x1e.activity.ConversationResponse\x12I\n\x12StreamConversation\x12\x1d.activity.ConversationRequest\x1a\x12.activity.Activity0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'activity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHANNEL']._serialized_start=407
  _globals['_CHANNEL']._serialized_end=476
  _globals['_DIRECTION']._serialized_start=478
  _globals['_DIRECTION']._serialized_end=532
  _globals['_CONVERSATIONREQUEST']._serialized_start=29
  _globals['_CONVERSATIONREQUEST']._serialized_end=186
  _globals['_ACTIVITY']._serialized_start=189
  _globals['_ACTIVITY']._serialized_end=326
  _globals['_CONVERSATIONRESPONSE']._serialized_start=328
  _globals['_CONVERSATIONRESPONSE']._serialized_end=405
  _globals['_ACTIVITYSERVICE']._serialized_start=535
  _globals['_ACTIVITYSERVICE']._serialized_end=709
# @@protoc_insertion_point(module_scope)
